### ISSUE TITLE
Check WP Poll style

### ISSUE THREAD

**Issue by davisshaver** [davisshaver/terminal#11]
Added a plugin for polls, WP Polls.

Charlotte Agenda uses it here: https://www.charlotteagenda.com/127111/poll-should-dot-dot-dot-change-its-dress-code-to-allow-shorts/

Make sure the style in terminal theme looks okay and if not, add some styles to make it fit.

Couple examples from Charlotte Agenda and another site below.

<img width="655" alt="screen shot 2018-08-28 at 9 16 29 am" src="https://user-images.githubusercontent.com/1636964/44725354-11cf7580-aaa3-11e8-9aa8-969a2b9bfe2e.png">

![attachment0](https://user-images.githubusercontent.com/1636964/44725404-2f044400-aaa3-11e8-86a2-6c9be6823ed1.jpeg)

**Comment by pixelyunicorn** [comment]
wp-polls is a challenge to style, mostly because it uses paragraphs and has styles difficult to override. So far, I got to to the point where it looks alright:

![image](https://user-images.githubusercontent.com/607807/45067038-3624e680-b08f-11e8-8fb0-0df512856486.png)

**Comment by davisshaver** [comment]
![screen shot 2018-09-11 at 10 12 17 am](https://user-images.githubusercontent.com/1636964/45365736-318a9180-b5ab-11e8-824b-00498eab3cc2.png)
