### ISSUE TITLE
Revamp color palette for LebTown to improve contrast for a117

### ISSUE THREAD

**Issue by davisshaver** [davisshaver/terminal#25]

**Comment by pixelyunicorn** [comment]
I'm poking around customizer right now and will and share a draft link in a couple mins

**Comment by pixelyunicorn** [comment]
This is what I have right now - https://leb.town/?customize_changeset_uuid=2135825b-366a-423d-b99a-1f187d1360e2 (draft customizer link at https://leb.town/wp/wp-admin/customize.php?changeset_uuid=2135825b-366a-423d-b99a-1f187d1360e2)

I have also found a couple critical things the theme customizer is missing (or I just can't the right setting):

Article card title colors (perhaps it's missing .terminal-sidebar-header-font)

![image](https://user-images.githubusercontent.com/607807/45599106-faa1ea80-b9b3-11e8-94ef-07bab5e5f288.png)

Footer color (I set the background to match the page color for now)

![image](https://user-images.githubusercontent.com/607807/45599194-4bfea980-b9b5-11e8-852b-8c48ef9c6464.png)

Ideally, there should also be a way to set "Post/page background color" and smaller article listing/sidebar card background independently. The white background on the post/page itself doesn't look right, but that's just me:

![image](https://user-images.githubusercontent.com/607807/45599272-97fe1e00-b9b6-11e8-8eb5-659de91f48d2.png)

**Comment by davisshaver** [comment]
Good stuff! I made new tickets for me to handle the missing options. I also published your changeset. Great use of the feature
