### ISSUE TITLE
Increase the story density in viewport by tweaking card styles

### ISSUE THREAD

**Issue by davisshaver** [davisshaver/terminal#26]
From critique in https://github.com/davisshaver/terminal/issues/7

> Leb.town has a lot of the same design quirks as onward state, notably that there is very little content visible at a time on the homepage, and too much whitespace.
> 
> ![image](https://user-images.githubusercontent.com/607807/45590536-50b95400-b908-11e8-980a-b7a4067d891e.png)
> 
> I also think a lot of the preview cards are way too big (taking up the entire height of the page), and it's hard to distinguish between title and body text. This can be solved by making the titled bold. You can also cut the header font size by 1/3 and text size by 1/4.
> 
> ![image](https://user-images.githubusercontent.com/607807/45590540-5ca51600-b908-11e8-9d22-292d3f10e9bc.png)
> 
> ![image](https://user-images.githubusercontent.com/607807/45590562-a857bf80-b908-11e8-9e83-f2117ba9fa19.png)

**Comment by pixelyunicorn** [comment]
In Customizer -> Typography

- all headline and header font weights should be set to 700
- set Headline Font Size to 24px
- I'm not sure how to set paragraph text just for the card previews, but set the font size to 16px, 17px, or 18px
