### ISSUE TITLE
Improve blockquote styling

### ISSUE THREAD

**Issue by davisshaver** [davisshaver/terminal#27]
Via critique in https://github.com/davisshaver/terminal/issues/7

> Blockquote styling should be improved, either with lighter text, thicker border, larger padding, different background, etc

**Comment by pixelyunicorn** [comment]
The background is optional, but this is how I implemented it

![image](https://user-images.githubusercontent.com/607807/45598115-7a27bd80-b9a4-11e8-8676-9e123cbe4c56.png)

**Comment by pixelyunicorn** [comment]
The left border is slightly darker in the commit
