### ISSUE TITLE
Increase size of mobile sharebar buttons

### ISSUE THREAD

**Issue by davisshaver** [davisshaver/terminal#29]
See https://github.com/davisshaver/terminal/issues/7

> On mobile, the social share bar icons are a bit small

**Comment by pixelyunicorn** [comment]
There seems to be !important overrides in the essb plugin, so I used transform rules to go around that

![image](https://user-images.githubusercontent.com/607807/45597883-afcaa780-b9a0-11e8-923b-dcd13c4c9a2e.png)
