### ISSUE TITLE
Replace external link emoji with proper icon

### ISSUE THREAD

**Issue by pixelyunicorn** [davisshaver/terminal#37]
On line 32 of `partials/content-loop.php`:

	$terminal_card_title = __( '🔗 External Link', 'terminal' );

The emoji is always rendered as a dark gray icon, which doesn't work well on gray backgrounds (see leb.town)

**Comment by davisshaver** [comment]
Replaced with `svg-icon` web components using https://github.com/frexy/svg-icon-webcomponent

Icons via https://glyph.smarticons.co/

<img width="386" alt="screen shot 2018-09-20 at 4 46 15 am" src="https://user-images.githubusercontent.com/1636964/45806947-3ed10b80-bc90-11e8-9e1b-59f0f8445913.png">

See https://github.com/davisshaver/terminal/commit/a77defe55761d4a7045003c4bb485a5bb49b6178
