### ISSUE TITLE
Integrate MailChimp form markup into ad block module

### ISSUE THREAD

**Issue by davisshaver** [davisshaver/terminal#5]
Could be done a few different ways, here's one.

Use McSub package - https://github.com/panoply/mcsub

Would maybe require some tweaks to markup. Also adding the package to `package.json` and importing in `index.js`. As well as integrating the API response and callback function.

It might be nice for users if we set a cookie indicating they are a newsletter subscriber so they don't have to do this every time.

**Comment by pixelyunicorn** [comment]
I made some progress on this but haven't gotten anything working yet

**Comment by davisshaver** [comment]
Finished in https://github.com/davisshaver/terminal/pull/16.

**Comment by pixelyunicorn** [comment]
You beat me to it, thanks!
