### ISSUE TITLE
Add meta refresh at 10mins for homepage

### ISSUE THREAD

**Issue by davisshaver** [davisshaver/terminal#8]
e.g. here is Billy Penn's `<meta http-equiv="refresh" content="600;url=?refresh=1" />`

**Comment by pixelyunicorn** [comment]
Is the ?refresh=1 flag necessary? It doesn't look like your page content is being cached.

**Comment by davisshaver** [comment]
@pixelyunicorn It should be cached, need to check on that. The query parameter is still useful for analytics though.
