### ISSUE TITLE
Add Time to Read indicator

### ISSUE THREAD

**Issue by davisshaver** [davisshaver/terminal#9]
<img width="345" alt="screen shot 2018-08-28 at 7 07 45 am" src="https://user-images.githubusercontent.com/1636964/44719367-15f29780-aa91-11e8-8834-56703569503c.png">

Example/basic algorithim https://github.com/ftlabs/time-to-read/blob/master/helpers/timeToRead.js

Background on how Medium does it https://help.medium.com/hc/en-us/articles/214991667-Read-time

**Comment by pixelyunicorn** [comment]
The best way to approach this is by creating a field that stores the time to read on each post, then calculating time to read on each save (and retroactively too)

**Comment by pixelyunicorn** [comment]
I'm not sure if you want to install another plugin, but https://wordpress.org/plugins/reading-time-wp/ calculates reading time on based on how Medium does it, and I can implement that

**Comment by davisshaver** [comment]
Handled in https://github.com/davisshaver/terminal/commit/dda3cd5261a1a9ced22c1e4f110560b9cdf832be
